### ISSUE TITLE
Datalist New Item button

### ISSUE THREAD

**Issue by Funies** [ITDSystems/alvex-datagrid#9]
Hi,

I have deployed alvex 3.0 on alfresco community 5.1.0.
After deploying alvex, the add item button on the datalist is disabled. We can create new data list but we cannot add new items.

Kind Regards

**Comment by aviriel** [comment]
Hi Funies,
Can you clarify, what Alfresco version do you use (5.1.d, e, f?) and what Alvex entensions did you install? Datagrid, datagrid + utils, all extensions in Alvex 3.0 zip?

**Comment by Funies** [comment]
Hi,

Thank you for the response.

This is the name of the zip file I downloaded from alvex website:
_alvex-3.0-20161005.110811-46.zip_. I just took the content of _Alfresco_
folder and add them to _tomcat/webapps/alfresco/web-inf/lib_ and the
content of _Share_ folder and put them under*
tomcat/webapps/share/web-inf/lib.*

I have attached a screenshot that shows the version of Alfresco we are
running; and a screenshot of the issue from user's point of view.

This is a clean alfresco with only Records manager
(alfresco-rm-community-2.4.b).

Kind Regards

**Comment by aviriel** [comment]
Please build new alvex-utils, alvex-datagrid and alvex-masterdata and replace old JARs with new ones. Or tomorrow morning new Alvex ZIP will be generated, you can take it, it contains all fixes.

**Comment by n00dl3s** [comment]
Hello,

I have installed datagrid and utils on alfresco 5.1.e/g/EA using SDK 3.0.0-beta5 and SDK 2.2, and all variations result in the "new item" in the datalist to be disabled. There are no errors in Chromes console.


Any help would be appreciated.

I have included a screen capture. 
![capture](https://cloud.githubusercontent.com/assets/26827185/24571993/e98c1dd0-1629-11e7-9a40-e3092642c4e5.PNG)



Thank you
Daniel

**Comment by Funies** [comment]
Hi,

Mine was resolved by installed the built that was done on the the 13th of
February. I would think that the current latest version/built should have
changes that were done then.
Let me know if you want me to share that particular built with you.

Kind regards

**Comment by aviriel** [comment]
Yes, we broke this page during last commit. But the same commit (and same code) fixed My Tasks page in Project Management add-on. So now we need some time to make both pages work as expected.

**Comment by errmerrged** [comment]
Hi, I'm also using Alfresco 5.1.e and I'm having the same problem, can you send me the link of what build did you use so I can try it? I can't find the build on Feb 13. Cheers!

**Comment by errmerrged** [comment]
Hi, I'm also using Alfresco 5.1.e and I'm having the same problem, I downloaded the Feb.13 build here http://nexus.itdhq.com/index.html#view-repositories but after installing the datagrid, util and masterdata jars, it still doesn't work. Any ideas?

**Comment by eadrobov** [comment]
I'm also using Alfresco 5.1.e and 5.2 Community it still doesn't work too

**Comment by errmerrged** [comment]
So I tried downloading another build version and the version from January 7,2017 is slightly working but **Edit** data item doesn't work, it redirects to another page instead of a pop-up to edit and when you hit submit it displays an error.

**Comment by errmerrged** [comment]
I tried using diff. versions of each jars and it seems, the **masterdata** and **utils** jars are working but **datagrid.jar** is not.

**Comment by ABakumenko** [comment]
I have the same problem with disabled New element button on DataList Page. Who solved it and can help?

**Comment by aviriel** [comment]
Fixed in today's build

**Comment by osavigne** [comment]
I´ve the same issue with 5.2 version and built from today sources, please help me how can i fix that, the new item button on any datalist is disabled after install this extension

**Comment by sokolovandrey** [comment]
таже проблема !!!!! на РАЗНЫХ компютерах НА РАЗНЫХ системах ставим чистую последнюю Alfresco собираю последнюю версию Alvex --- работает все кроме кнопки добавления новой записи в рееестре!!!!!
Пробовал на centos, macos, win10 версии альфреско русские....

**Comment by aviriel** [comment]
Sorry, but we cannot help you if we cannot reproduce an issue. What we do:
1. in *Alvex repo* execute ` mvn -P datagrid clean package` to build ZIP with alvex-datagrid and all dependencies. You can build it manually from here, but I expect that you forgot some dependencies and it's the reason of the issue.
2. In *target* folder find alvex-3.0-SNAPSHOT.zip. Extract it. Put all JARs from *repo* to *modules/platform*, all JARs from *share* to *modules/share*. We tested it on Alfresco 201707 and 201711.
3. Restart. Open swsdp site with default data list, create new item.
It works on win10, macos with any browser on client, linux on server

**Comment by sokolovandrey** [comment]
спасибо что хоть ответили.
Но слышать вы не хотите...
датагрид работает на работает кнопка "Новая запись" в реестрах... :(
Попробуйте сами на чистую систему (любую - я пробовал centos 7, macoc10.13.3, win10 64) поставить чистую новую альфреску и алвекс и вы очень удивитесь.... реестры НЕ работают
 p.s. да делаю по вашим инструкциям (они не полные - дайте знакомым попробовать по ним поставить у них врятли получится...) да помещаю в папки modules/platform, modules/share, и наведите пожалуйста порядок сTDSystems/alvex - если скачать zip по ссылке то половина не работает благо по git clone https://github.com/ITDSystems/alvex.git нормально собирается....

**Comment by aviriel** [comment]
Если Вы про реестры, то вы не в тот тикет и не в тот репозиторий вообще пишете. Тут у людей были проблемы с даталистами. Пойдемте обсуждать это в https://github.com/ITDSystems/alvex-registers. Там есть проблема с тем, что Aikau не развивается и версия 1.0.103 не работает. Поставьте Aikau 1.0.101.3, проверьте, что у Вас точно установлен пакет aikau-forms-runtime-support той же версии. Если кнопка не нажимается, значит не удалось подтянуть и построить форму, этим занимается aikau forms runtime service, проблема либо в его версии, либо в его отсутствии.

**Comment by sokolovandrey** [comment]
Вы извините за высказывания, но поймите меня правильно:
ООчень обидно за  Alvex поясню почему, получится так- я беру ставлю алфреску на чистую систему дальше наивно иду на алвекс,  оп
Посылает меня на Github ладно хорошо там все есть и даже инструкция, но абсолютно не понятно что дальше делать то как собирать то, ладно изучаем матчасть (не у алвекса) находим как поставить java maven дальше собираем весь алвекс и добавляем в альфреску оп почти все работает кроме кнопки + в реестрах замечу остальные кнопки работают..
Бред всего происходящего состоит в том что для установки программы не нужен программист (поставил и забыл) у вас так на прокатывает!!! Хорошо но сделайте хотяб видео инструкцию по установке (заодно проверите - я просто уверен если вы сейчас на чистую систему поставите свежую алфреску и далее по пунктам результат будет тот-же)
По фактам  Aikau 1.0.101.10 ставится как я понимаю альфреской как проверить остальные советы я не понимаю и в вашей документации этого нет!
Ставил все ваши пакеты зараз Aikau ваш там есть…
Самое обидное что самое интересное в алвексе это как раз реестры…
ПОЖАЛУЙСТА СДЕЛАЙТЕ видео инструкцию на установку полностью с нуля на https://github.com/ITDSystems/alvex <https://github.com/ITDSystems/alvex> !!!
Заранее благодарен
Соколов Андрей

**Comment by aviriel** [comment]
Андрей,
Мы понимаем, что Вам обидно. Но и Вы нас поймите. Мы больше не продаем Alvex. Мы не оказываем по нему услуги. Мы не занимаемся его развитием. Проект заморожен. Мы открыли то, что было, немного дописав это, чтобы оно работало на Alfresco 5, чтобы разработчики могли это использовать, если им правда нужно. Дальнейшим развитием и помощью мы (как люди, не как компания) занимаемся в режиме хобби. Поэтому не надо на нас ругаться.

Alvex - не "поставил и забыл", не "готовое решение", не "рекомендуется к использованию новичками и администраторами". Alvex, как готовая коробка, **мертв**. Если Вы ждете этого, не используйте его, используйте стандартную Alfresco, или лучше вообще не Alfresco. Тем более в упомянутых Вами реестрах, дажу нумерация не прикручена сейчас, потому что реестры новые и на Aikau.

Использовать Alvex сейчас - боль. Мы сами с трудом собираем (хотя с 1.0.101.3 в зависимостях правда собирается, а с 1.0.101.3-1.0.101.10 работает), потому что из Alfresco уволилась вся команда, которая разрабатывала интерфейс Share и Aikau. Наши pom.xml просто не могут достучаться до зависимостей, необходимых для сборки, потому что в Alfresco сейчас - бардак, их репозитории большую часть времени вообще не доступны. Новых людей на эту тему нанимать они не собираются, либо (по их словам 3 месяца назад) новые еще учатся. И это основная причина, почему Alvex как решение больше не существует, и мы закрыли эту тему. Но раз уж есть друзья-разработчики в Бразилии, Бельгии, Испании, Германии, которые продолжают это использовать, то мы не можем просто удалить репозитории. Разработчики, для которых это не единственный сторонний компонент для Alfresco, и которые постоянно сталкиваются с проблемами в Alfresco в последние годы, разберутся, как собрать и запустить. Если Вы хотите получить готовую коробку - считайте, что Alvex не существует.

Детали и официальная позиция компании: http://www.alvexcore.com/alvex-2.x-ru/

P.S. пакеты Aikau живут в папке webapps/share/WEB-INF/lib/ (после первого запуска системы). Я уверена, что у вас не только форма создания не открывается, но и форма редактирования (просто редактировать пока нечего). Это называется, Forms Runtime Service не найден или не тот.

**Comment by sokolovandrey** [comment]
Спасибо за ответ, жалко что проект умер.... А альтернативу не посоветуете?

28 марта 2018 г., 17:00 +0300, Oksana Kurysheva <notifications@github.com>, писал:

**Comment by aviriel** [comment]
Нет. Мы пока думаем о том, чтобы сделать SaaS-решение для реестров, но без Alfresco и тех архитектурных ограничений, которые она приносит, но пока не добрались. Чужих аналогов сходу не предложу.
